apiVersion: v1
kind: Secret
metadata:
  name: {{ template "besu.fullname" . }}-bootnode-keys
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.bootnode1.privateKey }}
  bootnode1Key: {{ .Values.bootnode1.privateKey | b64enc }}
  {{- end }}

  {{- if .Values.bootnode2.privateKey }}
  bootnode2Key: {{ .Values.bootnode2.privateKey | b64enc }}
  {{- end }}