bootnode:
  enabled: true

node:
  pvcSizeLimit: "1Gi"
  pvcStorageClass: "standard"
  memRequest: "1024Mi"
  memLimit: "2048Mi"
  cpuRequest: "100m"
  cpuLimit: "500m"

nodeSelector: {}
tolerations: []
affinity: {}

ingress_http:
  enabled: true
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   kubernetes.io/tls-acme: "true"
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-production
  path: /
  # hosts:
  #   - k8s.localhost.lan
  # tls:
  #  - secretName: clique-tls
  #    hosts:
  #      - k8s.localhost.lan

ingress_ws:
  enabled: false
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   kubernetes.io/tls-acme: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-production
  # path: /ws
  # hosts:
  #   - k8s.localhost.lan
  # tls:
  #  - secretName: clique-tls
  #    hosts:
  #      - k8s.localhost.lan

ingress_ethstats:
  enabled: false
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   kubernetes.io/tls-acme: "true"
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-production
  # path: /
  # hosts:
  #   - ethstats.apps.consensys.paris
  # tls:
  #  - secretName: clique-ethstats-tls
  #    hosts:
  #      - ethstats.apps.consensys.paris

ethstats:
  enabled: false
  # webSocketSecret: tralala
  # nodeSelector: {}
  # image:
  #   repository: puppeth/ethstats
  #   tag: latest
