---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: {{ template "pantheon.fullname" . }}-monitoring-namespace
    chart: {{ template "pantheon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: monitoring
