apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "pantheon.fullname" . }}-node
  labels:
    app: {{ template "pantheon.name" . }}
    chart: {{ template "pantheon.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: node
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pantheon.name" . }}
      release: {{ .Release.Name }}
      component: node
  template:
    metadata:
      labels:
        app: {{ template "pantheon.name" . }}
        release: {{ .Release.Name }}
        component: node
    spec:
      initContainers:
        - name: init-bootnode2
          image: byrnedo/alpine-curl
          command:
            - "sh"
            - "-c"
            - "curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 ${PANTHEON_BOOTNODE1_SERVICE_HOST}:8545/liveness"
      containers:
        - name: node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BOOTNODE1_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: pantheon-configmap
                  key: bootnode1PubKey
            - name: BOOTNODE2_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: pantheon-configmap
                  key: bootnode2PubKey
            - name: NODES_HTTP_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: pantheon-configmap
                  key: nodesHttpCorsOrigins
            - name: NODES_HOST_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: pantheon-configmap
                  key: nodesHostWhitelist
          volumeMounts:
            - name: genesis-config
              mountPath: /configs
              readOnly: true
          ports:
            - containerPort: 8545
              name: http
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 30303
              name: dev-p2p-tcp
              protocol: TCP
            - containerPort: 30303
              name: dev-p2p-udp
              protocol: UDP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec /opt/pantheon/bin/pantheon \
                --genesis-file=/configs/genesis.json \
                --rpc-http-enabled \
                --rpc-http-host=0.0.0.0 \
                --rpc-http-port=8545 \
                --rpc-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \
                --rpc-ws-enabled \
                --rpc-ws-host=0.0.0.0 \
                --rpc-ws-port=8546 \
                --host-whitelist=${NODES_HOST_WHITELIST} \
                --bootnodes=enode://${BOOTNODE1_PUBKEY}@${PANTHEON_BOOTNODE1_SERVICE_HOST}:30303,enode://${BOOTNODE2_PUBKEY}@${PANTHEON_BOOTNODE2_SERVICE_HOST}:30303
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30  
      volumes:
        - name: genesis-config
          configMap:
            name: pantheon-configmap
            items:
              - key: genesis.json
                path: genesis.json
