apiVersion: v1
kind: Secret
metadata:
  name: besu-orion-keys
  labels:
    app: orion-keys
type: Opaque
stringData:
  orion1.key: |-
    {"data":{"bytes":"hBsuQsGJzx4QHmFmBkNoI7YGnTmaZP4P+wBOdu56ljk="},"type":"unlocked"}
  orion2.key: |-
    {"data":{"bytes":"wjeHURxQJUqZvhjMv+lxoRlXYnX/mpm0Iu/ldBr32Qs="},"type":"unlocked"}
