apiVersion: v1
kind: Secret
metadata:
  name: quorum-member1-keys
  labels:
    app: quorum-member1-keys
  namespace: quorum
type: Opaque
stringData:
  nodekey: |-
    b9a4bd1539c15bcc83fa9078fe89200b6e9e802ae992f13cd83c853f16e8bed4
  accountkey: |-
    {"address":"c7e5b0fc0973e8bbc9f6bf4cced151da9608df90","crypto":{"cipher":"aes-128-ctr","ciphertext":"0d67b13099362ce4d883e5bceec2332650fe320914e8f2038d6ecdefc611572d","cipherparams":{"iv":"84cf8be5ce7df6d407389dae0b120266"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"24fcbbc1c78476cfef780e4a5a2b22c6d1e39fb5e3e95ec1a49da048f9e04658"},"mac":"05ce4d0bab3095eea9045767f2b0cee6385034d8a4c263d5dc8e0b1251bcbb0f"},"id":"6c18d511-29ea-47d3-b9b7-aa6d26ddd5b8","version":3}
  password.txt: |-
    Password
  tm.key: |-
    {"data":{"bytes":"Wl+xSyXVuuqzpvznOS7dOobhcn4C5auxkFRi7yLtgtA="},"type":"unlocked"}
  tm.pub: |-
    BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=
    