apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pantheon.fullname" . }}-validator-keys
  labels:
    app: {{ template "pantheon.name" . }}
    chart: {{ template "pantheon.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.validators.validator1.privateKey }}
  validator1Key: {{ .Values.validators.validator1.privateKey | b64enc }}
  {{- end }}

  {{- if .Values.validators.validator2.privateKey }}
  validator2Key: {{ .Values.validators.validator2.privateKey | b64enc }}
  {{- end }}

  {{- if .Values.validators.validator3.privateKey }}
  validator3Key: {{ .Values.validators.validator3.privateKey | b64enc }}
  {{- end }}

  {{- if .Values.validators.validator4.privateKey }}
  validator4Key: {{ .Values.validators.validator4.privateKey | b64enc }}
  {{- end }}