apiVersion: v1
name: pantheon-node
version: 0.1.0
description: Pantheon Nodes for a POA (IBFT2) Ethereum Blockchain
appVersion: 1.1.4
keywords:
  - validator
  - bootnode
  - node
  - pantheon
  - ethereum
  - pantheon
  - enterprise
  - blockchain
  - pegasys
  - consensys  
maintainers:
  - name: devops
    email: devops@pegasys.tech
icon: https://docs.pantheon.pegasys.tech/en/stable/favicon.ico
