apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion1
  labels:
    app: orion1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion1
  template:
    metadata:
      labels:
        app: orion1
    spec:
      containers:
        - name: orion1
          image: pegasyseng/orion:develop
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: key
              mountPath: /secrets
              readOnly: true
            - name: orion-conf
              mountPath: /configs-ro
              readOnly: true
            - name: orion-pubkey
              mountPath: /configs/keys
              readOnly: true
            - name: orion-init
              mountPath: /scripts/orion-init.sh
              subPath: orion-init.sh
          ports:
            - containerPort: 8888
              name: nodeport
              protocol: TCP
            - containerPort: 8080
              name: clientport
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - /scripts/orion-init.sh
          livenessProbe:
            httpGet:
              path: /upcheck
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /upcheck
              port: 8888
            initialDelaySeconds: 180
            periodSeconds: 30
      volumes:
        - name: orion-conf
          configMap:
            name: besu-configmap
            items:
              - key: orion1.conf
                path: orion.conf
        - name: orion-pubkey
          configMap:
            name: besu-configmap
            items:
              - key: orion1PubKey
                path: orion.pub
        - name: key
          secret:
            secretName: besu-orion-keys
            items:
              - key: orion1.key
                path: key
        - name: orion-init
          configMap:
            name: besu-orion-init
            defaultMode: 0777
