{{- $validatorNumber := "validator4" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $validatorNumber }}-sa
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ $validatorNumber }}-key-read-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [ {{ template "besu.fullname" . }}-{{ $validatorNumber }}-key ]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $validatorNumber }}-rb
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $validatorNumber }}-key-read-role
subjects:
  - kind: ServiceAccount
    name: {{ $validatorNumber }}-sa
    namespace: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "besu.fullname" . }}-{{ $validatorNumber }}
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
    component: {{ $validatorNumber }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "besu.name" . }}
      release: {{ .Release.Name }}
      component: {{ $validatorNumber }}
  serviceName: {{ template "besu.fullname" . }}-validator4
  template:
    metadata:
      labels:
        app: {{ template "besu.name" . }}
        release: {{ .Release.Name }}
        component: {{ $validatorNumber }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ $validatorNumber }}-sa
      initContainers:
      - name: init-bootnode
        image: byrnedo/alpine-curl
        command:
          - "sh"
          - "-c"
          - "curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 ${BESU_VALIDATOR1_SERVICE_HOST}:8545/liveness"
      containers:
      - name: {{ $validatorNumber }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.validators.cpuRequest }}"
            memory: "{{ .Values.validators.memRequest }}"
          limits:
            cpu: "{{ .Values.validators.cpuLimit }}"
            memory: "{{ .Values.validators.memLimit }}"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: VALIDATOR1_PUBKEY
            valueFrom:
              configMapKeyRef:
                name: besu-validators-configmap
                key: validator1PubKey
          - name: VALIDATOR2_PUBKEY
            valueFrom:
              configMapKeyRef:
                name: besu-validators-configmap
                key: validator2PubKey
        volumeMounts:
          - name: key
            mountPath: /secrets
            readOnly: true
          - name: genesis-config
            mountPath: /etc/genesis
            readOnly: true
          - name: config-toml
            mountPath: /etc/besu
            readOnly: true
          - name: data
            mountPath: /data
        ports:
          - name: http
            containerPort: {{ .Values.besuConfig.rpc.port }}
            protocol: TCP
          - name: ws
            containerPort: {{ .Values.besuConfig.ws.port }}
            protocol: TCP
          - name: graphql
            containerPort: {{ .Values.besuConfig.graphql.port }}
            protocol: TCP
          - name: p2p-tcp
            containerPort: {{ .Values.besuConfig.p2p.port }}
            protocol: TCP
          - name: p2p-udp
            containerPort: {{ .Values.besuConfig.p2p.port }}
            protocol: UDP
          - name: metrics
            containerPort: {{ .Values.besuConfig.metrics.port }}
            protocol: TCP
        command:
          - /bin/sh
          - -c
        args:
          - |
            exec /opt/besu/bin/besu \
              --node-private-key-file=/secrets/key \
              --config-file=/etc/besu/config.toml \
              --bootnodes=enode://${VALIDATOR1_PUBKEY}@${BESU_VALIDATOR1_SERVICE_HOST}:30303,enode://${VALIDATOR2_PUBKEY}@${BESU_VALIDATOR2_SERVICE_HOST}:30303
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: key
        secret:
          secretName: besu-{{ $validatorNumber }}-key
      - name: genesis-config
        configMap:
          name: besu-genesis-configmap
          items:
            - key: genesis.json
              path: genesis.json
      - name: config-toml
        configMap:
          name: besu-config-toml-configmap
      - name: data
        emptyDir:
          sizeLimit: "{{ .Values.validators.pvcSizeLimit }}"
