apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-validator1
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: validator1
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu.name" . }}
    release: {{ .Release.Name }}
    component: validator1
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: dev-p2p-udp
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: dev-p2p-tcp
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: http
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws