apiVersion: v1
kind: Secret
metadata:
  name: {{ template "besu.fullname" . }}-orion-keys
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ (.Files.Glob "orion1.key").AsSecrets | indent 2 }}
{{ (.Files.Glob "orion2.key").AsSecrets | indent 2 }}
{{ (.Files.Glob "orion3.key").AsSecrets | indent 2 }}
{{ (.Files.Glob "orion4.key").AsSecrets | indent 2 }}
