apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-orion1
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: orion1
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu.name" . }}
    release: {{ .Release.Name }}
    component: orion1
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodeport
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: clientport