apiVersion: v1
kind: Service
metadata:
  name: besu-orion3
  labels:
    app: orion3
spec:
  type: ClusterIP
  selector:
    app: orion3
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodeport
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: clientport
