apiVersion: v1
kind: Service
metadata:
  name: besu-orion4
  labels:
    app: orion4
spec:
  type: ClusterIP
  selector:
    app: orion4
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nodeport
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: clientport
