apiVersion: v1
kind: Service
metadata:
  name: quorum-node2privacy
  labels:
    app: node2privacy
  namespace: quorum
spec:
  type: ClusterIP
  selector:
    app: node2privacy
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 8547
      targetPort: 8547
      protocol: TCP
      name: graphql
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tm-tessera
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: tm-tessera-third-party
            